### PR TITLE
Fix German translations

### PR DESCRIPTION
**Pull request by tschoppi**
As already noted in PR #2372, the German translations are slightly suboptimal. This pull request aims at fixing translations and bringing them in line with how other text editors translate the actions from English to German.

As we are dependent on correct translations and prefer to get them directly from the upstream codebase instead of manually merging them in with every new release we offer these changes for free.

However, it would be very nice if you could merge in the changes using the normal GitHub flow instead of reattributing the changes to yourself. Credit where credit is due, and so on. If you need help with the integration of these changes into your private repository I can be of assistance.

I would like to thank @senfi for kicking this off, and @beatgutzwiller for his comments.

### CODE REVIEW

**Comment by stefanneculai** [comment]
@tschoppi we don't accept PR directly here because we do all the development in a private repo and the public code is committed from there. We would be happy to make this changes in such a way to give attribution, however, for that we would need your Github email which none of you guys have it listed public.

**Comment by tschoppi** [comment]
@stefanneculai, I have updated my profile in this regard. 

However, you should be able to pull in the branch of our fork into the private repository as well. That way the changes appear in both repositories. Maybe I'm missing something, but as far as I understand it this should work.

**Comment by stefanneculai** [comment]
@tschoppi the private repo is not compiled and the code is a little bit different.

**Comment by tschoppi** [comment]
I didn't think that was the case for the language files. In any case, I hope the changes get merged and shipped soon.

**Comment by stefanneculai** [comment]
@tschoppi merged. Thanks! 👍

**Pull request closed without merging**
